### ISSUE TITLE
App Data

### ISSUE THREAD

**Issue by gautampadiyar** [gautampadiyar/Khmd_Reader#2]
The app needs to get data from a blogger source and that needs working on. 

The testing for this may be done in a separate activity and can be integrated with the fragments after that issue is resolved.

**Comment by arjun-rao** [comment]
Okay I am going work on this, and try getting a list view setup with data from the blog, will be doing it in a fork on my account, under a branch called "blog_data_view" and then ill send u a pull request if it works

**Comment by arjun-rao** [comment]
This part has been successfully completed. Right now the way the app works is, it opens up MainActivity, where I have placed a button titled "Articles" to the new activity I have created, which is basically a listview of all the articles from the blog obtained via a yahoo pipe. Since we might want a splash screen, we can just repurpose the main activity for that, and call an intent to start the articleslist activity. The current code for this is on the master branch on my fork of your repo. I'll send you a pull request to merge this to your repo.
