### ISSUE TITLE
App Data Optimisation 

### ISSUE THREAD

**Issue by gautampadiyar** [gautampadiyar/Khmd_Reader#8]
App downloads almost 4.5 mb on each click on articles button.

1 Data needs to be saved/cached in some way
2 Pull to refresh needs to be added

**Comment by arjun-rao** [comment]
Gautam, this is primarily due to async download of all the images, I guess, as the text content will hardly take up o much of data. So I guess we can cache images somewhere maybe add sd card request as part of permissions, and store the images along with app, and check for those images before downloading?

**Comment by gautampadiyar** [comment]
No. When we switch to Volley all caching will AUTOMATICALLY be taken care of. That's our best option.

**Comment by arjun-rao** [comment]
Cool :)
